### ISSUE TITLE
New md files aren't converting to html

### ISSUE THREAD

**Issue by patricktrainer** [patricktrainer/static-site#5]
`md_to_html()` isn't being called before `main()`

The `<li>` is being made in the template, but not the actually linked file

**Comment by walbarello** [comment]
Try adding to index.py:

> def md_to_html():
>     # Your code for converting Markdown to HTML goes here
>     # Make sure to generate the linked file as well
> 
> def main():
>     # Your main code logic goes here
> 
> # Call md_to_html() before calling main()
> md_to_html()
> main()
>
